### PR TITLE
Adds "70 JavaScript Interview Questions"

### PR DESCRIPTION
**Pull request by valentinperignon**
One new link in the Javascript category.

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Review by ryan-blunden — COMMENTED** [review]
Thanks for the pr @valentinperignon!

**Review by ryan-blunden — APPROVED** [review]

**Review by ryan-blunden — APPROVED** [review]
Awesome contribution @valentinperignon!

**Comment by dincerunal** [comment]
Nice :))

**Comment by ryan-blunden** [comment]
Closing in favor of https://github.com/DopplerHQ/awesome-interview-questions/pull/229 which resolves the merge conflict.

**Pull request closed without merging**
