### PR TITLE
Removing dead links

### PR DESCRIPTION
**Pull request by bharadwaj-pendyala**
Ran a scraper to verify dead links throughout the ReadMe file. I have found below four links that are not working as expected from Comprehensive Lists and Data Science Stack. 

https://www.recruityourninja.com/technical-interview-questions-frontend-candidates/
https://www.recruityourninja.com/technical-interview-questions-backend-candidates/
https://www.recruityourninja.com/technical-interview-questions-devops-candidates/
https://recruityourninja.com/technical-interview-questions-data-scientist/

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]
Ye, the links expired.
Peace :heart:

**Comment by bharadwaj-pendyala** [comment]
Thanks @53jk1

**Comment by bharadwaj-pendyala** [comment]
@MaximAbramchuck Could you please look into this PR while you are free? This is approved and ready for merge.

**Comment by Piccirello** [comment]
Thanks for the PR!

**Pull request merged**
